//package database.greendao;
//
//import android.database.Cursor;
//import android.database.sqlite.SQLiteStatement;
//
//import com.sailing.android.bayonet.database.entity.BayonetInfo;
//
//import org.greenrobot.greendao.AbstractDao;
//import org.greenrobot.greendao.Property;
//import org.greenrobot.greendao.database.DatabaseStatement;
//import org.greenrobot.greendao.internal.DaoConfig;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * DAO for table "B_SSSB_SBXX".
//*/
//public class BayonetInfoDao extends AbstractDao<BayonetInfo, Void> {
//
//    public static final String TABLENAME = "B_SSSB_SBXX";
//
//    /**
//     * Properties of entity BayonetInfo.<br/>
//     * Can be used for QueryBuilder and for referencing column names.
//     */
//    public static class Properties {
//        public final static Property Xh = new Property(0, int.class, "xh", false, "XH");
//        public final static Property Sbbh = new Property(1, String.class, "sbbh", false, "SBBH");
//        public final static Property Sbmc = new Property(2, String.class, "sbmc", false, "SBMC");
//        public final static Property Sblx = new Property(3, String.class, "sblx", false, "SBLX");
//        public final static Property Sbdl = new Property(4, String.class, "sbdl", false, "SBDL");
//        public final static Property Sbms = new Property(5, String.class, "sbms", false, "SBMS");
//        public final static Property Bzwzdm = new Property(6, String.class, "bzwzdm", false, "BZWZDM");
//        public final static Property Jd = new Property(7, double.class, "jd", false, "JD");
//        public final static Property Wd = new Property(8, double.class, "wd", false, "WD");
//    }
//
//
//    public BayonetInfoDao(DaoConfig config) {
//        super(config);
//    }
//
//    public BayonetInfoDao(DaoConfig config, DaoSession daoSession) {
//        super(config, daoSession);
//    }
//
//    @Override
//    protected final void bindValues(DatabaseStatement stmt, BayonetInfo entity) {
//        stmt.clearBindings();
//        stmt.bindLong(1, entity.getXh());
//
//        String sbbh = entity.getSbbh();
//        if (sbbh != null) {
//            stmt.bindString(2, sbbh);
//        }
//
//        String sbmc = entity.getSbmc();
//        if (sbmc != null) {
//            stmt.bindString(3, sbmc);
//        }
//
//        String sblx = entity.getSblx();
//        if (sblx != null) {
//            stmt.bindString(4, sblx);
//        }
//
//        String sbdl = entity.getSbdl();
//        if (sbdl != null) {
//            stmt.bindString(5, sbdl);
//        }
//
//        String sbms = entity.getSbms();
//        if (sbms != null) {
//            stmt.bindString(6, sbms);
//        }
//
//        String bzwzdm = entity.getBzwzdm();
//        if (bzwzdm != null) {
//            stmt.bindString(7, bzwzdm);
//        }
//        stmt.bindDouble(8, entity.getJd());
//        stmt.bindDouble(9, entity.getWd());
//    }
//
//    @Override
//    protected final void bindValues(SQLiteStatement stmt, BayonetInfo entity) {
//        stmt.clearBindings();
//        stmt.bindLong(1, entity.getXh());
//
//        String sbbh = entity.getSbbh();
//        if (sbbh != null) {
//            stmt.bindString(2, sbbh);
//        }
//
//        String sbmc = entity.getSbmc();
//        if (sbmc != null) {
//            stmt.bindString(3, sbmc);
//        }
//
//        String sblx = entity.getSblx();
//        if (sblx != null) {
//            stmt.bindString(4, sblx);
//        }
//
//        String sbdl = entity.getSbdl();
//        if (sbdl != null) {
//            stmt.bindString(5, sbdl);
//        }
//
//        String sbms = entity.getSbms();
//        if (sbms != null) {
//            stmt.bindString(6, sbms);
//        }
//
//        String bzwzdm = entity.getBzwzdm();
//        if (bzwzdm != null) {
//            stmt.bindString(7, bzwzdm);
//        }
//        stmt.bindDouble(8, entity.getJd());
//        stmt.bindDouble(9, entity.getWd());
//    }
//
//    @Override
//    public Void readKey(Cursor cursor, int offset) {
//        return null;
//    }
//
//    @Override
//    public BayonetInfo readEntity(Cursor cursor, int offset) {
//        BayonetInfo entity = new BayonetInfo( //
//            cursor.getInt(offset + 0), // xh
//            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sbbh
//            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sbmc
//            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // sblx
//            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // sbdl
//            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // sbms
//            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // bzwzdm
//            cursor.getDouble(offset + 7), // jd
//            cursor.getDouble(offset + 8) // wd
//        );
//        return entity;
//    }
//
//    @Override
//    public void readEntity(Cursor cursor, BayonetInfo entity, int offset) {
//        entity.setXh(cursor.getInt(offset + 0));
//        entity.setSbbh(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
//        entity.setSbmc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
//        entity.setSblx(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
//        entity.setSbdl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
//        entity.setSbms(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
//        entity.setBzwzdm(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
//        entity.setJd(cursor.getDouble(offset + 7));
//        entity.setWd(cursor.getDouble(offset + 8));
//     }
//
//    @Override
//    protected final Void updateKeyAfterInsert(BayonetInfo entity, long rowId) {
//        // Unsupported or missing PK type
//        return null;
//    }
//
//    @Override
//    public Void getKey(BayonetInfo entity) {
//        return null;
//    }
//
//    @Override
//    public boolean hasKey(BayonetInfo entity) {
//        // TODO
//        return false;
//    }
//
//    @Override
//    protected final boolean isEntityUpdateable() {
//        return true;
//    }
//
//}
