//package database.greendao;
//
//
//import org.greenrobot.greendao.AbstractDao;
//import org.greenrobot.greendao.AbstractDaoSession;
//import org.greenrobot.greendao.database.Database;
//import org.greenrobot.greendao.identityscope.IdentityScopeType;
//import org.greenrobot.greendao.internal.DaoConfig;
//
//import java.util.Map;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * {@inheritDoc}
// *
// * @see AbstractDaoSession
// */
//public class DaoSession extends AbstractDaoSession {
//
//    private final DaoConfig bayonetInfoDaoConfig;
//    private final DaoConfig vehicleBrandInfoDaoConfig;
//
//    private final BayonetInfoDao bayonetInfoDao;
//    private final VehicleBrandInfoDao vehicleBrandInfoDao;
//
//    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap) {
//        super(db);
//
//        bayonetInfoDaoConfig = daoConfigMap.get(BayonetInfoDao.class).clone();
//        bayonetInfoDaoConfig.initIdentityScope(type);
//
//        vehicleBrandInfoDaoConfig = daoConfigMap.get(VehicleBrandInfoDao.class).clone();
//        vehicleBrandInfoDaoConfig.initIdentityScope(type);
//
//        bayonetInfoDao = new BayonetInfoDao(bayonetInfoDaoConfig, this);
//        vehicleBrandInfoDao = new VehicleBrandInfoDao(vehicleBrandInfoDaoConfig, this);
//
////        registerDao(BayonetInfo.class, bayonetInfoDao);
////        registerDao(VehicleBrandInfo.class, vehicleBrandInfoDao);
//    }
//
//    public void clear() {
//        bayonetInfoDaoConfig.clearIdentityScope();
//        vehicleBrandInfoDaoConfig.clearIdentityScope();
//    }
//
//    public BayonetInfoDao getBayonetInfoDao() {
//        return bayonetInfoDao;
//    }
//
//    public VehicleBrandInfoDao getVehicleBrandInfoDao() {
//        return vehicleBrandInfoDao;
//    }
//
//}
