///*
//package database.greendao;
//
//import android.database.Cursor;
//import android.database.sqlite.SQLiteStatement;
//
//import com.sailing.android.bayonet.database.entity.VehicleBrandInfo;
//
//import org.greenrobot.greendao.AbstractDao;
//import org.greenrobot.greendao.Property;
//import org.greenrobot.greendao.database.DatabaseStatement;
//import org.greenrobot.greendao.internal.DaoConfig;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
//*/
///**
// * DAO for table "B_KKQP_CXXX_CLPPKS".
//*//*
//
//public class VehicleBrandInfoDao extends AbstractDao<VehicleBrandInfo, Void> {
//
//    public static final String TABLENAME = "B_KKQP_CXXX_CLPPKS";
//
//    */
///**
//     * Properties of entity VehicleBrandInfo.<br/>
//     * Can be used for QueryBuilder and for referencing column names.
//     *//*
//
//    public static class Properties {
//        public final static Property Xh = new Property(0, int.class, "xh", false, "XH");
//        public final static Property Cxzlksbh = new Property(1, int.class, "cxzlksbh", false, "CXZLKSBH");
//        public final static Property Cxzlksmc = new Property(2, String.class, "cxzlksmc", false, "CXZLKSMC");
//        public final static Property Clppbh = new Property(3, int.class, "clppbh", false, "CLPPBH");
//        public final static Property Clppmc = new Property(4, String.class, "clppmc", false, "CLPPMC");
//        public final static Property Clzlbh = new Property(5, int.class, "clzlbh", false, "CLZLBH");
//        public final static Property Cllxbh = new Property(6, int.class, "cllxbh", false, "CLLXBH");
//        public final static Property Tp1 = new Property(7, String.class, "tp1", false, "TP1");
//    }
//
//
//    public VehicleBrandInfoDao(DaoConfig config) {
//        super(config);
//    }
//
//    public VehicleBrandInfoDao(DaoConfig config, DaoSession daoSession) {
//        super(config, daoSession);
//    }
//
//    @Override
//    protected final void bindValues(DatabaseStatement stmt, VehicleBrandInfo entity) {
//        stmt.clearBindings();
//        stmt.bindLong(1, entity.getXh());
//        stmt.bindLong(2, entity.getCxzlksbh());
//
//        String cxzlksmc = entity.getCxzlksmc();
//        if (cxzlksmc != null) {
//            stmt.bindString(3, cxzlksmc);
//        }
//        stmt.bindLong(4, entity.getClppbh());
//
//        String clppmc = entity.getClppmc();
//        if (clppmc != null) {
//            stmt.bindString(5, clppmc);
//        }
//        stmt.bindLong(6, entity.getClzlbh());
//        stmt.bindLong(7, entity.getCllxbh());
//
//        String tp1 = entity.getTp1();
//        if (tp1 != null) {
//            stmt.bindString(8, tp1);
//        }
//    }
//
//    @Override
//    protected final void bindValues(SQLiteStatement stmt, VehicleBrandInfo entity) {
//        stmt.clearBindings();
//        stmt.bindLong(1, entity.getXh());
//        stmt.bindLong(2, entity.getCxzlksbh());
//
//        String cxzlksmc = entity.getCxzlksmc();
//        if (cxzlksmc != null) {
//            stmt.bindString(3, cxzlksmc);
//        }
//        stmt.bindLong(4, entity.getClppbh());
//
//        String clppmc = entity.getClppmc();
//        if (clppmc != null) {
//            stmt.bindString(5, clppmc);
//        }
//        stmt.bindLong(6, entity.getClzlbh());
//        stmt.bindLong(7, entity.getCllxbh());
//
//        String tp1 = entity.getTp1();
//        if (tp1 != null) {
//            stmt.bindString(8, tp1);
//        }
//    }
//
//    @Override
//    public Void readKey(Cursor cursor, int offset) {
//        return null;
//    }
//
//    @Override
//    public VehicleBrandInfo readEntity(Cursor cursor, int offset) {
//        VehicleBrandInfo entity = new VehicleBrandInfo( //
//            cursor.getInt(offset + 0), // xh
//            cursor.getInt(offset + 1), // cxzlksbh
//            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cxzlksmc
//            cursor.getInt(offset + 3), // clppbh
//            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // clppmc
//            cursor.getInt(offset + 5), // clzlbh
//            cursor.getInt(offset + 6), // cllxbh
//            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // tp1
//        );
//        return entity;
//    }
//
//    @Override
//    public void readEntity(Cursor cursor, VehicleBrandInfo entity, int offset) {
//        entity.setXh(cursor.getInt(offset + 0));
//        entity.setCxzlksbh(cursor.getInt(offset + 1));
//        entity.setCxzlksmc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
//        entity.setClppbh(cursor.getInt(offset + 3));
//        entity.setClppmc(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
//        entity.setClzlbh(cursor.getInt(offset + 5));
//        entity.setCllxbh(cursor.getInt(offset + 6));
//        entity.setTp1(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
//     }
//
//    @Override
//    protected final Void updateKeyAfterInsert(VehicleBrandInfo entity, long rowId) {
//        // Unsupported or missing PK type
//        return null;
//    }
//
//    @Override
//    public Void getKey(VehicleBrandInfo entity) {
//        return null;
//    }
//
//    @Override
//    public boolean hasKey(VehicleBrandInfo entity) {
//        // TODO
//        return false;
//    }
//
//    @Override
//    protected final boolean isEntityUpdateable() {
//        return true;
//    }
//
//}
//*/
